logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log
  pattern:
    level: '%5p [${spring.application.name:}]'
server:
  port: 8080
spring:
  application:
    name: netwatch-server
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true
netwatch:
  event-listener:
    port: 8990