logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log
  pattern:
    level: '%5p [${spring.application.name:}]'
server:
  port: 8080
application:
  version: netgaze-revision
spring:
  application:
    name: netgaze-server
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true