logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    name: ${spring.application.home:.}/logs/${spring.application.name}.log
  pattern:
    level: '%5p [${spring.application.name:}]'
server:
  port: 8080
application:
  version: netgaze-revision
spring:
  application:
    name: netgaze-server
  datasource:
    driver-class-name: "${DB_DRIVER:org.postgresql.Driver}"
    url: "${DB_URL:jdbc:postgresql://localhost:5432/netgaze}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:root}"
    hikari:
      minimumIdle: 5
      maximumPoolSize: 5
      idleTimeout: 30000
      poolName: DataSourceServicePool
      maxLifetime: 1800000
      connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /docs
    tryItOutEnabled: true