services:
  postgres:
    image: postgres:16.1
    command: -c 'max_connections=500'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
      - ~/NetGaze/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U root -d postgres'" ]
      interval: 10s
      timeout: 10s
      retries: 300
    restart: unless-stopped
    shm_size: 512mb
    networks:
      - netgaze-network

  postgres-ui:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_SERVER_JSON_FILE: /pg-ui-config/servers.json
    volumes:
      - ./config/pg-ui-servers.json:/pg-ui-config/servers.json
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:5050/misc/ping" ]
      interval: 10s
      timeout: 10s
      retries: 300
    restart: unless-stopped
    networks:
      - netgaze-network


  grafana:
    image: grafana/grafana:main-ubuntu
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./config/grafana-ds.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./config/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./config/grafana-dash.json:/var/lib/grafana/dashboards/dash.json:ro
      - ./config/icon.svg:/usr/share/grafana/public/img/grafana_icon.svg:ro
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-I", "-XGET", "http://localhost:3000" ]
      interval: 10s
      timeout: 10s
      retries: 300
    restart: unless-stopped
    networks:
      - netgaze-network

networks:
  netgaze-network: